name: Create Release 📦
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ⚙️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Release 🛠 (Windows)
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          project_path: "./src"
        env:
          CGO_ENABLED: 1

      - name: Build Release 🛠 (macOS)
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_command: apt update && apt install -y clang
          goos: darwin
          goarch: amd64
          project_path: "./src"
        env:
          CGO_ENABLED: 1
